import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { join } from 'node:path'

/**
 * BIZ-04 — no-touch calculators rule must live in the production prompt.
 *
 * Why parse the source instead of importing SYSTEM_PROMPT:
 * - SYSTEM_PROMPT is intentionally not exported (keeps the module's public
 *   surface minimal). Exporting just for tests would be an anti-pattern.
 * - Reading the source via readFileSync is the cheapest, most robust way to
 *   guarantee the prompt contract cannot be silently removed in a refactor.
 *
 * If any of these assertions fails, CI blocks the merge and forces a human
 * review of why the integrity rules were changed.
 */
describe('BIZ-04: system prompt integrity rules', () => {
  const source = readFileSync(
    join(process.cwd(), 'lib', 'ai-insights-generator.ts'),
    'utf8'
  )

  it('contains the REGLAS DE INTEGRIDAD NUMERICA header', () => {
    expect(source).toContain('REGLAS DE INTEGRIDAD NUMERICA')
  })

  it('forbids recomputation explicitly', () => {
    expect(source).toMatch(/NUNCA recalcules/i)
  })

  it('names the calculators as the only source of truth', () => {
    expect(source).toMatch(/UNICA fuente de verdad numerica/i)
  })

  it('forbids fabricating data not present in ReportData', () => {
    expect(source).toMatch(/NO lo inventes/i)
  })

  it('forbids approximations like ~ or aprox', () => {
    // The prompt must call out approximation patterns as prohibited.
    expect(source).toMatch(/~1\.250|aprox\./i)
  })

  it('enumerates every calculator name so the LLM knows the full set', () => {
    const calculators = [
      'cash_discrepancy',
      'deleted_invoices',
      'deleted_products',
      'waste_analysis',
      'inventory_deviation',
      'correlation',
      'conclusions',
    ]
    for (const c of calculators) {
      expect(source).toContain(c)
    }
  })

  it('blocks benchmarks / seasonality inference', () => {
    expect(source).toMatch(/benchmarks/i)
    expect(source).toMatch(/estacionalidad/i)
  })

  it('handles zero/null fields as "sin datos suficientes" instead of fabrication', () => {
    expect(source).toMatch(/0 o null/)
    expect(source).toMatch(/sin datos suficientes/)
  })
})

/**
 * B3 — GDPR pseudonymization instructions must live in the production prompt.
 *
 * When the prompt encounters `__EMP_N__` tokens (generated by
 * lib/privacy/pseudonymize.ts), Claude must treat them as opaque identifiers
 * and not attempt to invent real names or rewrite to generic terms. Losing
 * this instruction would visibly degrade the narrative ("varios empleados"
 * instead of "__EMP_1__" which the client-side restores to "Juan García").
 */
describe('B3: GDPR pseudonymization prompt instructions', () => {
  const source = readFileSync(
    join(process.cwd(), 'lib', 'ai-insights-generator.ts'),
    'utf8'
  )

  it('contains the PROTECCION DE DATOS (GDPR) header', () => {
    expect(source).toContain('PROTECCION DE DATOS (GDPR)')
  })

  it('mentions the __EMP_<numero>__ token format so Claude recognizes it', () => {
    expect(source).toContain('__EMP_<numero>__')
  })

  it('explicitly forbids inventing a real name for opaque tokens', () => {
    expect(source).toMatch(/NO inventes un nombre real/i)
  })

  it('forbids collapsing tokens into generic terms', () => {
    expect(source).toMatch(/varios empleados/i)
  })

  it('imports the pseudonymization helpers from lib/privacy', () => {
    expect(source).toContain("from './privacy/pseudonymize'")
    expect(source).toContain('pseudonymizeReportData')
    expect(source).toContain('depseudonymizeInsights')
  })
})
